Map<String, String> flags = {
  "USD": "us.png",
  "EUR": "eur.png",
  "AUD": "au.png",
  "AZN": "az.png",
  "GBP": "gb.png",
  "AMD": "am.png",
  "BYN": "by.png",
  "BGN": "bg.png",
  "BRL": "br.png",
  "HUF": "hu.png",
  "HKD": "hk.png",
  "DKK": "dk.png",
  "INR": "in.png",
  "KZT": "kz.png",
  "CAD": "ca.png",
  "KGS": "kg.png",
  "CNY": "cn.png",
  "MDL": "md.png",
  "NOK": "no.png",
  "PLN": "pl.png",
  "RON": "ro.png",
  "RUB": "ru.png",
  "SGD": "sg.png",
  "TJS": "tj.png",
  "TRY": "tr.png",
  "TMT": "tm.png",
  "UZS": "uz.png",
  "UAH": "ua.png",
  "CZK": "cz.png",
  "SEK": "se.png",
  "CHF": "ch.png",
  "ZAR": "za.png",
  "KRW": "kr.png",
  "JPY": "jp.png"
};

